name: "Muiltievent pipeline workflow"

on:
    push:
        branches:
            - master
            - test

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Runing on master push"
              run: echo "Runing on master push"

