name: "Muiltievent pipeline workflow"

on:
    push:
        branches:
            - master
            - test
    pull_request:
        branches:
            - master

jobs:
    on-push:
        if: github.event == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Runing on master push"
              run: echo "Runing on master push"

    on-pull-request:
        if: github.event =='pull'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request on master"